


class AppConstants:
    CONFIG_FILE_NAME = "Config.ini"

    SPLASH_WINDOW_TITLE = "Loading GenDoc"
    SPLASH_WINDOW_WIDTH = 500
    SPLASH_WINDOW_HEIGHT = 400

    MAIN_WINDOW_TITLE = "GenDoc"
    MAIN_WINDOW_WIDTH = 700
    MAIN_WINDOW_HEIGHT = 600

    RECORDER_WINDOW_TITLE = "GenDoc Recorder Screen"
    RECORDER_WINDOW_WIDTH = 300
    RECORDER_WINDOW_HEIGHT = 250

    RECORDER_CANVAS_WIDTH = 150
    RECORDER_CANVAS_HEIGHT = 140

    EXPLORER_WINDOW_TITLE = "Screenshot Explorer"
    EXPLORER_WINDOW_WIDTH = 900
    EXPLORER_WINDOW_HEIGHT = 600
